<?php /*
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCvlqPA6QP4+1OYxvWZtXiExmCN
dlFFOFI+1x5kujuEqEMY6PsTvREtSNgEGSsbos0KmWbEeGsqJVoSeRcGVHo3yYUF
021BPlNVpTbzI3U5nMGgvLbRWuaH8zLG0yTtRtvujWHluXylLu1Fix2GuXhP5HCv
9vjrWnG4pur5P8aCCwIDAQAB
-----END PUBLIC KEY-----
*/ ?>